EXTENSIONS = {
    'application/gzip': 'GZ',
    'application/json': 'JSON',
    'application/msword': 'DOC',
    'application/pdf': 'PDF', 'image/tiff': 'TIFF',
    'application/rtf': 'RTF',
    'application/vnd.ms-excel': 'XLS',
    'application/vnd.ms-powerpoint': 'PPT',
    'application/vnd.oasis.opendocument.presentation': 'ODP',
    'application/vnd.oasis.opendocument.spreadsheet': 'ODS',
    'application/vnd.oasis.opendocument.text': 'ODT',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation': 'PPTX',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': 'XLSX',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'DOCX',
    'application/x-bzip2': 'BZ2',
    'application/x-tar': 'TAR',
    'application/xml': 'XML',
    'application/zip': 'ZIP',
    'audio/mpeg': 'MP3',
    'audio/webm': 'WEBA',
    'image/gif': 'GIF',
    'image/jpeg': 'JPG',
    'image/png': 'PNG',
    'image/webp': 'WEBP',
    'text/css': 'CSS',
    'text/csv': 'CSV',
    'text/html': 'HTML',
    'text/javascript': 'JS',
    'text/plain': 'TXT',
    'video/mp4': 'MP4',
    'video/mpeg': 'MPEG',
    'video/webm': 'WEBM',
}
