SUBJECTS = {
    '-': 'Keines / Anderes',
    'BG': 'Bildnerisches Gestalten',
    'BI': 'Biologie',
    'BL': 'Begleitetes Lernen',
    'CH': 'Chemie',
    'DE': 'Deutsch',
    'EN': 'Englisch',
    'FR': 'Französisch',
    'GG': 'Geografie',
    'GS': 'Geschichte',
    'HW': 'Hauswirtschaft',
    'IN': 'Informatik',
    'KS': 'Klassenstunde',
    'MA': 'Mathematik',
    'MU': 'Musik',
    'NT': 'Natur & Technik',
    'PB': 'Politische Bildung',
    'PH': 'Philosophie',
    'PS': 'Physik',
    'RE': 'Religionskunde & Ethik',
    'SP': 'Sport',
    'TG': 'Technisches Gestalten',
    'WR': 'Wirtschaft & Recht',
    'SAM': 'Schwerpunktfach Anwendungen der Mathematik',
    'SPS': 'Schwerpunktfach Physik',
    'SBI': 'Schwerpunktfach Biologie',
    'SCH': 'Schwerpunktfach Chemie',
    'SBG': 'Schwerpunktfach Bildnerisches Gestalten',
    'SES': 'Schwerpunktfach Spanisch',
    'SIT': 'Schwerpunktfach Italienisch',
    'SMU': 'Schwerpunktfach Musik',
    'SWR': 'Schwerpunktfach Wirtschaft & Recht',
    'EAM': 'Ergänzungsfach Anwendungen der Mathematik',
    'EBG': 'Ergänzungsfach Bildnerisches Gestalten',
    'EBI': 'Ergänzungsfach Biologie',
    'ECH': 'Ergänzungsfach Chemie',
    'EGG': 'Ergänzungsfach Geografie',
    'EGS': 'Ergänzungsfach Geschichte',
    'EIN': 'Ergänzungsfach Informatik',
    'EMU': 'Ergänzungsfach Musik',
    'EPH': 'Ergänzungsfach Philosophie',
    'EPP': 'Ergänzungsfach Pädagogik & Psychologie',
    'EPS': 'Ergänzungsfach Physik',
    'ERE': 'Ergänzungsfach Religionskunde & Ethik',
    'ESP': 'Ergänzungsfach Sport',
    'EWR': 'Ergänzungsfach Wirtschaft & Recht',
    'F': 'Freifach',
}
